
import { db } from "./server/db.js";
import { supportRequests } from "./shared/schema.js";
import { eq } from "drizzle-orm";

async function createFeedbackTestData() {
  console.log("Creating test feedback data...");

  const feedbackData = [
    // Existing 5 records
    {
      full_name: "Nguyễn Văn An",
      email: "nguyenvanan@example.com",
      subject: "Báo lỗi: Không thể đăng nhập",
      content: "Tôi không thể đăng nhập vào hệ thống từ sáng nay. Khi nhập username và password thì bị báo lỗi 'Invalid credentials'.",
      type: "feedback",
      feedback_type: "bug_report",
      detailed_description: "Lỗi xảy ra từ khoảng 8:00 sáng nay. Tôi đã thử clear cache và cookies nhưng vẫn không được. Browser: Chrome 120, OS: Windows 11.",
      status: "pending",
      assigned_to_id: 1,
      assigned_at: new Date(),
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      full_name: "Trần Thị Bình",
      email: "tranthibibinh@example.com", 
      subject: "Yêu cầu tính năng: Dark mode",
      content: "Tôi muốn có tính năng dark mode cho ứng dụng để dễ sử dụng vào ban đêm.",
      type: "feedback",
      feedback_type: "feature_request",
      feature_type: "Giao diện người dùng",
      detailed_description: "Dark mode sẽ giúp giảm mỏi mắt khi sử dụng ứng dụng trong môi trường ánh sáng yếu. Có thể thêm toggle switch ở góc phải trên cùng.",
      status: "processing",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 24 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 24 * 60 * 60 * 1000),
      updated_at: new Date(),
    },
    {
      full_name: "Lê Minh Cường",
      email: "leminhcuong@example.com",
      subject: "Khiếu nại: Dịch vụ chậm",
      content: "Dịch vụ xử lý của hệ thống rất chậm, mất nhiều thời gian để load dữ liệu.",
      type: "feedback", 
      feedback_type: "complaint",
      detailed_description: "Thời gian load trang thường mất từ 10-15 giây, đặc biệt là trang danh sách content. Điều này ảnh hưởng đến công việc hàng ngày.",
      attachment_url: "https://example.com/speed-test-report.pdf",
      status: "completed",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      response_content: "Chúng tôi đã tối ưu hóa database và cải thiện tốc độ load. Vui lòng kiểm tra lại.",
      responder_id: 1,
      response_time: new Date(Date.now() - 24 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
    {
      full_name: "Phạm Thị Dung",
      email: "phamthidung@example.com",
      subject: "Đề xuất: Thêm tính năng export Excel",
      content: "Đề xuất thêm tính năng export dữ liệu ra file Excel để tiện theo dõi và báo cáo.",
      type: "feedback",
      feedback_type: "suggestion", 
      feature_type: "Xuất dữ liệu",
      detailed_description: "Tính năng export Excel sẽ giúp người dùng dễ dàng tạo báo cáo và chia sẻ dữ liệu với đồng nghiệp. Nên hỗ trợ export theo bộ lọc.",
      status: "pending",
      assigned_to_id: 2,
      assigned_at: new Date(),
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      full_name: "Hoàng Văn Em",
      email: "hoangvanem@example.com",
      subject: "Khác: Câu hỏi về bảo mật",
      content: "Tôi có thắc mắc về chính sách bảo mật dữ liệu của hệ thống.",
      type: "feedback",
      feedback_type: "other",
      detailed_description: "Tôi muốn biết dữ liệu cá nhân có được mã hóa không và được lưu trữ ở đâu. Có tuân thủ các quy định về bảo vệ dữ liệu cá nhân không?",
      status: "processing",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 6 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 6 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    
    // 20 records mới
    {
      full_name: "Vũ Thị Hoa",
      email: "vuthihoa@example.com",
      subject: "Báo lỗi: Lỗi 500 khi upload file",
      content: "Khi tôi upload file ảnh, hệ thống báo lỗi 500 Internal Server Error.",
      type: "feedback",
      feedback_type: "bug_report",
      detailed_description: "Lỗi xảy ra với file ảnh PNG có dung lượng > 5MB. File nhỏ hơn thì upload bình thường.",
      attachment_url: "https://example.com/error-screenshot.png",
      status: "pending",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 30 * 60 * 1000),
      created_at: new Date(Date.now() - 30 * 60 * 1000),
      updated_at: new Date(Date.now() - 30 * 60 * 1000),
    },
    {
      full_name: "Đỗ Minh Hải",
      email: "dominhhải@example.com",
      subject: "Yêu cầu tính năng: Push notification",
      content: "Tôi muốn nhận thông báo đẩy khi có nội dung mới được assigned cho tôi.",
      type: "feedback",
      feedback_type: "feature_request",
      feature_type: "Thông báo",
      detailed_description: "Push notification sẽ giúp tôi biết ngay khi có công việc mới cần xử lý, không cần phải refresh trang liên tục.",
      status: "pending",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 45 * 60 * 1000),
      created_at: new Date(Date.now() - 45 * 60 * 1000),
      updated_at: new Date(Date.now() - 45 * 60 * 1000),
    },
    {
      full_name: "Bùi Thị Lan",
      email: "buithilan@example.com",
      subject: "Khiếu nại: Mất dữ liệu sau khi cập nhật",
      content: "Sau lần cập nhật hệ thống hôm qua, tôi không thấy một số bài viết đã xử lý.",
      type: "feedback",
      feedback_type: "complaint",
      detailed_description: "Khoảng 15 bài viết tôi đã approve từ tuần trước giờ không còn trong danh sách. Tôi cần khôi phục lại dữ liệu này.",
      status: "processing",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 2 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 3 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 60 * 60 * 1000),
    },
    {
      full_name: "Ngô Văn Tuấn",
      email: "ngovantuan@example.com",
      subject: "Đề xuất: Thêm filter theo ngày tạo",
      content: "Đề xuất thêm bộ lọc theo ngày tạo content để dễ dàng tìm kiếm.",
      type: "feedback",
      feedback_type: "suggestion",
      feature_type: "Tìm kiếm và lọc",
      detailed_description: "Hiện tại chỉ có filter theo assigned date, nên thêm filter theo created date sẽ giúp tìm nội dung cũ dễ hơn.",
      status: "completed",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      response_content: "Cảm ơn đề xuất! Chúng tôi đã thêm bộ lọc theo ngày tạo trong phiên bản mới.",
      responder_id: 2,
      response_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      full_name: "Trịnh Thị Mai",
      email: "trinhthimai@example.com",
      subject: "Khác: Hỏi về quy trình approve",
      content: "Tôi muốn biết quy trình approve content cụ thể như thế nào?",
      type: "feedback",
      feedback_type: "other",
      detailed_description: "Là nhân viên mới, tôi cần hiểu rõ các bước cần làm khi approve một content và những tiêu chí đánh giá.",
      status: "completed",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      response_content: "Tôi đã gửi tài liệu hướng dẫn quy trình vào email của bạn. Có thắc mắc gì thêm hãy liên hệ.",
      responder_id: 1,
      response_time: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      full_name: "Lý Văn Đức",
      email: "lyvanduc@example.com",
      subject: "Báo lỗi: Không thể xóa comment",
      content: "Button xóa comment không hoạt động, click vào không có phản hồi gì.",
      type: "feedback",
      feedback_type: "bug_report",
      detailed_description: "Lỗi xuất hiện trên browser Firefox 118. Trên Chrome thì hoạt động bình thường.",
      status: "processing",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 90 * 60 * 1000),
      created_at: new Date(Date.now() - 90 * 60 * 1000),
      updated_at: new Date(Date.now() - 60 * 60 * 1000),
    },
    {
      full_name: "Phan Thị Nga",
      email: "phanthinga@example.com",
      subject: "Yêu cầu tính năng: Bulk action",
      content: "Tôi muốn có tính năng chọn nhiều content cùng lúc để thực hiện action.",
      type: "feedback",
      feedback_type: "feature_request",
      feature_type: "Quản lý hàng loạt",
      detailed_description: "Bulk approve, bulk reject, bulk assign sẽ giúp tiết kiệm thời gian khi xử lý nhiều content có tính chất tương tự.",
      status: "pending",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 15 * 60 * 1000),
      created_at: new Date(Date.now() - 15 * 60 * 1000),
      updated_at: new Date(Date.now() - 15 * 60 * 1000),
    },
    {
      full_name: "Cao Minh Quân",
      email: "caominhquan@example.com",
      subject: "Khiếu nại: Giao diện trên mobile khó sử dụng",
      content: "Giao diện trên điện thoại khó nhìn và khó thao tác.",
      type: "feedback",
      feedback_type: "complaint",
      detailed_description: "Các button quá nhỏ, table không responsive tốt trên màn hình nhỏ. Tôi phải zoom in/out liên tục.",
      status: "pending",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 4 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 4 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000),
    },
    {
      full_name: "Đinh Thị Hương",
      email: "dinhthihuong@example.com",
      subject: "Đề xuất: Thống kê chi tiết hơn",
      content: "Đề xuất thêm chart thống kê theo từng category và source.",
      type: "feedback",
      feedback_type: "suggestion",
      feature_type: "Báo cáo và thống kê",
      detailed_description: "Dashboard hiện tại chỉ có thống kê tổng quan. Nếu có chart theo category, source sẽ giúp phân tích xu hướng tốt hơn.",
      status: "processing",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 6 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 7 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    {
      full_name: "Võ Văn Hùng",
      email: "vovanhung@example.com",
      subject: "Khác: Đổi mật khẩu",
      content: "Tôi muốn thay đổi mật khẩu nhưng không tìm thấy chức năng này.",
      type: "feedback",
      feedback_type: "other",
      detailed_description: "Tôi đã tìm trong trang Profile và Settings nhưng không thấy option đổi password. Có thể hướng dẫn tôi không?",
      status: "completed",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 8 * 60 * 60 * 1000),
      response_content: "Chức năng đổi mật khẩu nằm trong trang Profile > Bảo mật. Tôi đã cập nhật để dễ tìm hơn.",
      responder_id: 1,
      response_time: new Date(Date.now() - 6 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 8 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000),
    },
    {
      full_name: "Tạ Thị Linh",
      email: "tathilinh@example.com",
      subject: "Báo lỗi: Lỗi khi search có dấu",
      content: "Khi search với từ khóa có dấu tiếng Việt thì không ra kết quả.",
      type: "feedback",
      feedback_type: "bug_report",
      detailed_description: "Ví dụ search 'Sài Gòn' thì không ra gì, nhưng search 'Sai Gon' thì có kết quả. Unicode encoding có vấn đề.",
      status: "pending",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 3 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 3 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    {
      full_name: "Đặng Văn Phúc",
      email: "dangvanphuc@example.com",
      subject: "Yêu cầu tính năng: Auto-assign",
      content: "Muốn có tính năng tự động assign content theo workload của từng người.",
      type: "feedback",
      feedback_type: "feature_request",
      feature_type: "Phân công tự động",
      detailed_description: "Hệ thống nên theo dõi số lượng content đang pending của mỗi user và tự động assign cho người có ít việc nhất.",
      status: "processing",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 12 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 12 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 10 * 60 * 60 * 1000),
    },
    {
      full_name: "Huỳnh Thị Oanh",
      email: "huynhthioanh@example.com",
      subject: "Khiếu nại: Session timeout quá nhanh",
      content: "Tôi bị logout khỏi hệ thống sau 30 phút không hoạt động.",
      type: "feedback",
      feedback_type: "complaint",
      detailed_description: "30 phút là quá ngắn, đặc biệt khi đang đọc content dài. Nên tăng lên ít nhất 2 tiếng hoặc có warning trước khi logout.",
      status: "completed",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      response_content: "Chúng tôi đã tăng session timeout lên 2 tiếng và thêm warning 5 phút trước khi logout.",
      responder_id: 2,
      response_time: new Date(Date.now() - 24 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
    {
      full_name: "Lương Văn Sơn",
      email: "luongvanson@example.com",
      subject: "Đề xuất: Keyboard shortcuts",
      content: "Thêm phím tắt để thao tác nhanh hơn khi xử lý content.",
      type: "feedback",
      feedback_type: "suggestion",
      feature_type: "Trải nghiệm người dùng",
      detailed_description: "Ví dụ: Ctrl+A để approve, Ctrl+R để reject, Ctrl+N để next content. Sẽ tăng tốc độ xử lý đáng kể.",
      status: "pending",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 5 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 5 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    {
      full_name: "Quách Thị Thu",
      email: "quachthithu@example.com",
      subject: "Khác: Hỏi về backup dữ liệu",
      content: "Dữ liệu của hệ thống có được backup định kỳ không?",
      type: "feedback",
      feedback_type: "other",
      detailed_description: "Tôi lo lắng về việc mất dữ liệu, muốn biết chính sách backup và khôi phục dữ liệu của công ty.",
      status: "pending",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 8 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 8 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 8 * 60 * 60 * 1000),
    },
    {
      full_name: "Dương Văn Tài",
      email: "duongvantai@example.com",
      subject: "Báo lỗi: Duplicate content không được detect",
      content: "Hệ thống không phát hiện được content trùng lặp.",
      type: "feedback",
      feedback_type: "bug_report",
      detailed_description: "Tôi thấy có 2 content có nội dung giống hệt nhau nhưng hệ thống không báo duplicate. Cần cải thiện thuật toán detect.",
      attachment_url: "https://example.com/duplicate-examples.pdf",
      status: "processing",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 9 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 9 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 7 * 60 * 60 * 1000),
    },
    {
      full_name: "Mạc Thị Vân",
      email: "macthivan@example.com",
      subject: "Yêu cầu tính năng: Template cho comment",
      content: "Muốn có template sẵn cho các comment thường dùng.",
      type: "feedback",
      feedback_type: "feature_request",
      feature_type: "Mẫu nội dung",
      detailed_description: "Các comment như 'Nội dung không phù hợp', 'Cần bổ sung thông tin', 'Đã approve' nên có template để chọn nhanh.",
      status: "pending",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 10 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 10 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 10 * 60 * 60 * 1000),
    },
    {
      full_name: "Bạch Văn Vũ",
      email: "bachvanvu@example.com",
      subject: "Khiếu nại: Không thể copy text từ content",
      content: "Text trong khung content không thể select và copy được.",
      type: "feedback",
      feedback_type: "complaint",
      detailed_description: "Khi muốn copy một đoạn text để search Google hoặc dịch thì không copy được. Có thể do CSS disable select.",
      status: "completed",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      response_content: "Đã fix lỗi CSS, giờ có thể select và copy text trong content.",
      responder_id: 1,
      response_time: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
    {
      full_name: "Ông Thị Xuân",
      email: "ongthixuan@example.com",
      subject: "Đề xuất: Thêm tag cho content",
      content: "Đề xuất thêm hệ thống tag để phân loại content chi tiết hơn.",
      type: "feedback",
      feedback_type: "suggestion",
      feature_type: "Phân loại nội dung",
      detailed_description: "Ngoài category, nên có tag như #viral, #trending, #educational để dễ filter và tìm kiếm content sau này.",
      status: "processing",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 11 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 11 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 9 * 60 * 60 * 1000),
    },
    {
      full_name: "Tiêu Văn Yến",
      email: "tieuvuyen@example.com",
      subject: "Khác: Training cho nhân viên mới",
      content: "Có thể tổ chức training về cách sử dụng hệ thống không?",
      type: "feedback",
      feedback_type: "other",
      detailed_description: "Nhiều nhân viên mới chưa quen với interface và workflow của hệ thống. Cần có session training hoặc video hướng dẫn.",
      status: "pending",
      assigned_to_id: 1,
      assigned_at: new Date(Date.now() - 13 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 13 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 13 * 60 * 60 * 1000),
    },
    {
      full_name: "Khúc Văn Zung",
      email: "khucvanzung@example.com",
      subject: "Báo lỗi: Timezone hiển thị sai",
      content: "Thời gian hiển thị trong hệ thống không đúng với timezone Việt Nam.",
      type: "feedback",
      feedback_type: "bug_report",
      detailed_description: "Tất cả timestamp đều chậm hơn 7 tiếng so với giờ thực. Có vẻ hệ thống đang dùng UTC mà chưa convert sang GMT+7.",
      status: "completed",
      assigned_to_id: 2,
      assigned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      response_content: "Đã fix timezone, tất cả thời gian giờ hiển thị theo giờ Việt Nam (GMT+7).",
      responder_id: 2,
      response_time: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    }
  ];

  try {
    // Delete existing feedback data to avoid duplicates
    await db.delete(supportRequests).where(eq(supportRequests.type, 'feedback'));
    console.log("🗑️ Cleared existing feedback data");

    for (const feedback of feedbackData) {
      await db.insert(supportRequests).values(feedback);
      console.log(`✅ Created feedback: ${feedback.subject}`);
    }
    
    console.log("\n🎉 Test feedback data created successfully!");
    console.log(`📊 Created ${feedbackData.length} feedback records`);
    
  } catch (error) {
    console.error("❌ Error creating feedback test data:", error);
  }
}

// Run the script
createFeedbackTestData()
  .then(() => {
    console.log("✅ Script completed");
    process.exit(0);
  })
  .catch((error) => {
    console.error("❌ Script failed:", error);
    process.exit(1);
  });
