
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: emso-elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=emso-logs
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: emso-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  fluentd:
    build:
      context: .
      dockerfile: Dockerfile.fluentd
    container_name: emso-fluentd
    volumes:
      - ./logs:/app/logs:ro
      - ./fluentd.conf:/fluentd/etc/fluent.conf
      - ./elasticsearch-template.json:/etc/fluent/emso-template.json
    ports:
      - "24224:24224"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local
